name: Build ImmortalWrt

permissions:
  contents: write

concurrency:
  group: immortalwrt-${{ github.event.inputs.profile }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        description: "请选择mtk路由器型号"
        required: true
        options:
          - glinet_gl-mt3000
        default: glinet_gl-mt3000
      custom_router_ip:
        description: "请设置路由器的管理地址 格式:192.168.x.1 或 10.x.x.1"
        required: true
        default: "192.168.8.1"
      enable_store:
        description: "集成 store 商店"
        required: false
        type: boolean
        default: false
      include_docker:
        description: |
          是否编译 Docker 插件
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'
      enable_pppoe:
        description: "是否配置PPPoE拨号信息?"
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'
      pppoe_account:
        description: "宽带账号 (若启用PPPoE)"
        required: false
      pppoe_password:
        description: "宽带密码 (若启用PPPoE)"
        required: false


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions
        run: |
          chmod +x ${{ github.workspace }}/build.sh

      - name: Save Custom Router IP into OpenWrt files
        run: |
          mkdir -p "${{ github.workspace }}/custom"
          echo "${{ github.event.inputs.custom_router_ip }}" > "${{ github.workspace }}/custom/custom_router_ip.txt"
          echo "您设置的路由器管理地址是:${{ github.event.inputs.custom_router_ip }}"
          # 后续步骤会将该文件映射到路由器/etc/config/custom_router_ip.txt 以便用于开机脚本99-custom.sh读取用户设置的ip


      - name: Validate PPPoE Inputs
        run: |
          if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
            if [[ -z "${{ inputs.pppoe_account }}" || -z "${{ inputs.pppoe_password }}" ]]; then
              echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
              exit 1
            fi
          fi

      - name: Enable Store integration
        run: |
          if [ "${{ github.event.inputs.enable_store }}" == "true" ]; then
            echo 'CUSTOM_PACKAGES="$CUSTOM_PACKAGES luci-app-store"' >> scripts/custom-packages.sh
            echo "✅ 已追加 luci-app-store"
          else
            echo "❎ 未启用 luci-app-store"
          fi


      - name: Build Wireless ImmortalWrt
        run: |
          profile="${{ github.event.inputs.profile }}"
          echo "Building for profile: $profile"
          include_docker="${{ github.event.inputs.include_docker }}"
          # 默认平台
          echo "platform=mediatek/filogic" >> $GITHUB_ENV

          tag=mediatek-filogic-openwrt-24.10.5

          docker run --rm -i \
            --user root \
            -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
            -v "${{ github.workspace }}/files/etc/uci-defaults:/home/build/immortalwrt/files/etc/uci-defaults" \
            -v "${{ github.workspace }}/custom:/home/build/immortalwrt/files/etc/config" \
            -v "${{ github.workspace }}/files/etc/opkg/arch.conf:/home/build/immortalwrt/files/etc/opkg/arch.conf" \
            -v "${{ github.workspace }}/scripts:/home/build/immortalwrt/scripts" \
            -v "${{ github.workspace }}/build.sh:/home/build/immortalwrt/build.sh" \
            -e PROFILE=$profile \
            -e INCLUDE_DOCKER=$include_docker \
            -e ENABLE_PPPOE=${{ inputs.enable_pppoe }} \
            -e PPPOE_ACCOUNT=${{ inputs.pppoe_account }} \
            -e PPPOE_PASSWORD=${{ inputs.pppoe_password }} \
            immortalwrt/imagebuilder:$tag /bin/bash /home/build/immortalwrt/build.sh


      - name: Create info
        run: |
          if [ "${{ github.event.inputs.include_docker }}" == "yes" ]; then
            extra_content="### 默认带docker"
            echo -e "\n $extra_content" >> ${{ github.workspace }}/config/info.md
          else
            echo -e "NO docker"
          fi
          custom_router_ip="${{ github.event.inputs.custom_router_ip }}"
          extra_content_ip="#### 管理地址 $custom_router_ip"
          echo -e "\n $extra_content_ip" >> ${{ github.workspace }}/config/info.md

      - name: Upload ImmortalWrt as release assets
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.profile }}-${{ github.run_id }}
          name: ImmortalWrt-${{ github.event.inputs.profile }}-${{ github.run_id }}
          body_path: config/info.md
          files: |
            bin/targets/${{ env.platform }}/*
